### PR TITLE
#167289235 An agent/admin should be able to update a property

### PR DESCRIPTION
**Pull request by dnuwa**
#### What does this PR do?
- An agent/admin should be able to update a property
#### Description of Task to be completed?
- update/edit advert details 
#### How should this be manually tested?
- git checkout `ft-update-advert-167289235`
- run the command `npm run install` then `npm run dev` to run the app
- hit the endpoint PATCH`http://localhost:5000/api/v1/property/4`
- specify the fields that you'd like to edit in the body for example:
```
{
	"price":"10000000",
	"status":"updated",
	"type":"updated"
}
```
#### Any background context
- The user must be an agent/admin
- An advert can only be updated by the owner
#### What are the relevant pivotal tracker stories?
- [#167289235](https://www.pivotaltracker.com/story/show/167289235)
#### Screenshots (if appropriate)
Screenshot (41)

### CODE REVIEW

**Comment by Jordybastien** [comment]
`Naming conventions`
>-What are the relevant pivotal tracker stories? 
I think what could be more useful here is a link instead of just the story id so that someone can automatically view the story when needed.
your code is well written I should learn a thing or two from it

**Comment by ekumamait** [comment]
> `Naming conventions`
> 
> > -What are the relevant pivotal tracker stories?
> > I think what could be more useful here is a link instead of just the story id so that someone can automatically view the story when needed.
> > your code is well written I should learn a thing or two from it

@Jordybastien the way @dnuwa has done it is actually correct since it is a story id with a hyperlink

**Comment by ekumamait** [comment]
@dnuwa how should this be manually tested needs to be included and it should be a step by step guide even including installing packages and activating the environment if exists

**Comment by Jordybastien** [comment]
@ekumamait I wasn't aware of that, I always copied my links into that section, Thank you

**Comment by dnuwa** [comment]
> @dnuwa how should this be manually tested needs to be included and it should be a step by step guide even including installing packages and activating the environment if exists

@ekumamait thanks for pointing this out and it has been worked on.

**Pull request merged**
